version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: df-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    links:
      - db

  db:
    image: mariadb:latest
    container_name: df-db
    volumes:
      - ./db/config/charset.cnf:/etc/mysql/conf.d/charset.cnf
      - ./db/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: df-btg-root-pass
      MYSQL_DATABASE: df-btg-db
      MYSQL_USER: df-btg-user
      MYSQL_PASSWORD: df-btg-pass
    expose:
      - 3306
    ports:
      - "3306:3306"

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: admin-df
#    ports:
#      - '8888:80'
#    environment:
#      - PMA_ARBITRARY=1
#      - PMA_HOST=mysql
#    depends_on:
#      - db